# Generated by Django 5.2.13 on 2026-05-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_stores',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_subject',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sysadmin', 'SysAdmin'), ('admin', 'Admin'), ('seller', 'Seller')], default='seller', max_length=20),
        ),
    ]
