# Generated by Django 5.2.15 on 2026-07-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_stores_user_google_subject_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
