# Generated by Django 5.2.13 on 2026-05-03 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_assigned_stores_user_google_subject_user_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_name', models.CharField(blank=True, max_length=180)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('sell', 'Sell'), ('restock', 'Restock'), ('regularize', 'Regularize'), ('reorder', 'Reorder'), ('password', 'Password'), ('login', 'Login')], max_length=20)),
                ('resource_type', models.CharField(max_length=60)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
